# Generated by Django 5.2.4 on 2025-08-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_review_app', '0004_topic_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='division',
            field=models.CharField(blank=True, choices=[('A', 'Division A'), ('B', 'Division B'), ('C', 'Division C')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='roll_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='semester',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6')], null=True),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='division',
            field=models.CharField(blank=True, choices=[('A', 'Division A'), ('B', 'Division B'), ('C', 'Division C')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='semester',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6')], null=True),
        ),
    ]
