# Generated by Django 5.2.4 on 2025-08-18 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_review_app', '0008_topic_teacher_alter_topic_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
