# Generated by Django 5.2.4 on 2025-08-19 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_review_app', '0009_alter_topic_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgroup',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
